[hugetlbfs]
max_page_size = "huge"

[funk]
max_account_records = 1048576
heap_size_gib = 20
max_database_transactions = 1024

[runtime]
heap_size_gib = 4

[runtime.limits]
max_live_slots = 512
max_vote_accounts = 32
max_total_banks = 64
max_fork_width = 16

[layout]
verify_tile_count = 1
exec_tile_count = 1
writer_tile_count = 1

[tiles.shred]
max_pending_shred_sets = 512

[tiles.gui]
enabled = false
max_http_connections = 16
max_websocket_connections = 16
send_buffer_size_mb = 128
