[hugetlbfs]
max_page_size = "huge"

[accounts]
max_accounts = 1048576
file_size_gib = 20

[runtime.limits]
max_live_slots = 512
max_fork_width = 16

[layout]
verify_tile_count = 1
execrp_tile_count = 1

[tiles.shred]
max_pending_shred_sets = 512

[tiles.gui]
enabled = false
max_http_connections = 16
max_websocket_connections = 16
send_buffer_size_mb = 128
