[layout]
    exec_tile_count = 10
[gossip]
    port = 9723
    entrypoints = ["{validator_ip}:8001"]
[blockstore]
    shred_max = 16777216
    block_max = 4096
    txn_max = 1024
    idx_max = 8192
    alloc_max = 10737418240
    file = "{blockstore_path}"
[funk]
    heap_size_gib = 20
    max_account_records = 1048576
    max_database_transactions = 4096
[tiles]
    [tiles.shred]
        max_pending_shred_sets = 16384
    [tiles.repair]
        repair_intake_listen_port = 9294
        repair_serve_listen_port = 8034
    [tiles.replay]
        snapshot_url = "http://{validator_ip}:8899/snapshot.tar.bz2"
    [tiles.metric]
        prometheus_listen_address = "0.0.0.0"
        prometheus_listen_port = 7999
[consensus]
    vote = false
    expected_shred_version = 36600
[paths]
    identity_key = "{keys}/fd-identity-keypair.json"
    vote_account = "{keys}/fd-vote-keypair.json"
[log]
    path = "{ledger_dir}/firedancer-dev.log"
    level_stderr = "INFO"
    level_logfile = "NOTICE"
