[snapshots]
    cluster = "testnet"
[gossip]
    entrypoints = [
        "entrypoint.testnet.solana.com:8001",
        "entrypoint2.testnet.solana.com:8001",
    ]
[funk]
    heap_size_gib = 40
    max_account_records = 200_000_000
[layout]
    gossvf_tile_count = 1
