name: Test Fuzz Regressions
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  make-fuzz:
    name: Test Fuzz Regressions on ${{ matrix.feature_set }}
    strategy:
      matrix:
        feature_set: [modern]
    runs-on:
      group: github-v1
    env:
      MACHINE: linux_clang_combi_${{ matrix.feature_set }}
      EXTRAS: fuzz asan ubsan
    steps:
      - uses: actions/checkout@v4

      - name: Build Fuzz Tests
        run: make -j -Otarget fuzz-test

      - name: Run Fuzz Tests Against Corpora
        run: make -k -j -Otarget run-fuzz-test
